name: ci

on:
  pull_request:
    branches:
      - zig-stable

jobs:
  linter:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "${{ github.event.pull_request.head.repo.full_name }}"
        ref: "${{ github.event.pull_request.head.ref }}"
    - name: Setup zig
      uses: mlugg/setup-zig@v2
      with:
        version: 'master'
    - name: Check zig is canonical
      shell: 'bash'
      run: zig fmt --check .
  example:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "${{ github.event.pull_request.head.repo.full_name }}"
        ref: "${{ github.event.pull_request.head.ref }}"
    - name: Setup zig
      uses: mlugg/setup-zig@v2
      with:
        version: 'master'
    - name: Test building example
      shell: 'bash'
      run: |
        set -x
        unset ZIG_LOCAL_CACHE_DIR
        env -C "${GITHUB_WORKSPACE}/example" zig build
        set -f
        ${GITHUB_WORKSPACE}/example/zig-out/bin/example
        set +f
  maintainance:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "${{ github.event.pull_request.head.repo.full_name }}"
        ref: "${{ github.event.pull_request.head.ref }}"
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 'master'

    - name: Test updating
      shell: 'bash'
      run: zig build -Dupdate -Dverbose
