name: ci

on:
  pull_request:
    branches:
      - stable

jobs:
  linter:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"
      - name: Check zig is canonical
        shell: 'bash'
        run: zig fmt --check .
  example:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"
      - name: Test building example
        shell: 'bash'
        run: |
          set -x
          unset ZIG_LOCAL_CACHE_DIR
          env -C "${GITHUB_WORKSPACE}/example" zig build
          set -f
          ${GITHUB_WORKSPACE}/example/zig-out/bin/example
          set +f
  maintainance:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"

      - name: Test updating
        shell: 'bash'
        run: zig build -Dupdate -Dverbose
